fix inspect-table link in main docstring
delta-incubator/delta-kernel-rs pull request #289
Opened 2024-07-19 23:20 UTC by zachschuermann

tiny fix for 404 in docs

2024-07-22 23:45 UTC, nicklan requested changes

2024-07-22 23:45 UTC, nicklan commented on kernel/src/lib.rs
> +//! [inspect-table] example.
good catch, but the link we actually probably want is https://github.com/delta-incubator/delta-kernel-rs/tree/main/kernel/examples/read-table-single-threaded (and call it `read-table-single-threaded`). Maybe link to https://github.com/delta-incubator/delta-kernel-rs/tree/main/kernel/examples/read-table-multi-threaded as well and just say a more complex multi-threaded example also exists

2024-07-26 18:54 UTC, nicklan approved these changes

2024-07-27 05:16 UTC, hntd187 approved these changes

2024-07-27 13:30 UTC, MrPowers approved these changes

2024-07-28 17:44 UTC, merged