change default features to be none
delta-incubator/delta-kernel-rs pull request #339
Opened 2024-09-17 19:46 UTC by zachschuermann

remove sync-engine from default features so there are no features enabled by default. note this will required delta-rs to change their dependency specification to likely turn on `arrow-conversion` feature flag.

2024-09-17 20:01 UTC, hntd187 requested changes
Can we also update the readme to reflect that users have to opt into a client via the features flag?

2024-09-17 21:01 UTC, nicklan approved these changes
I'm good with this as long as we update the README as steve requested

2024-10-01 18:19 UTC, hntd187 approved these changes
Looks good, thanks for the doc updates

2024-10-01 18:40 UTC, nicklan requested changes
Can you mention that the sync engine only supports local storage

2024-10-01 18:52 UTC, nicklan approved these changes

2024-10-01 18:56 UTC, merged